# Generated by Django 5.2.7 on 2025-10-05 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('weight_kg', models.FloatField()),
                ('height_cm', models.FloatField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('activity_level', models.FloatField(choices=[(1.2, 'Sedentary (little or no exercise)'), (1.375, 'Lightly active (light exercise/sports 1-3 days/week)'), (1.55, 'Moderately active (moderate exercise/sports 3-5 days/week)'), (1.725, 'Very active (hard exercise/sports 6-7 days a week)'), (1.9, 'Super active (very hard exercise/physical job)')])),
                ('goal', models.CharField(choices=[('lose', 'Weight Loss'), ('maintain', 'Weight Maintenance'), ('gain', 'Muscle Gain')], max_length=10)),
                ('dietary_preferences', models.CharField(blank=True, help_text='e.g., vegetarian, vegan, low-carb', max_length=200)),
                ('allergies', models.TextField(blank=True, help_text='Comma-separated list, e.g., peanuts, shellfish, dairy')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
