# Generated by Django 5.2.7 on 2025-10-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.FloatField()),
                ('protein_g', models.FloatField()),
                ('carbs_g', models.FloatField()),
                ('fat_g', models.FloatField()),
                ('tags', models.CharField(blank=True, help_text='e.g., breakfast, vegetarian, gluten-free', max_length=200)),
                ('recipe', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='activity_level',
            field=models.FloatField(blank=True, choices=[(1.2, 'Sedentary (little or no exercise)'), (1.375, 'Lightly active (light exercise/sports 1-3 days/week)'), (1.55, 'Moderately active (moderate exercise/sports 3-5 days/week)'), (1.725, 'Very active (hard exercise/sports 6-7 days a week)'), (1.9, 'Super active (very hard exercise/physical job)')], null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(blank=True, choices=[('lose', 'Weight Loss'), ('maintain', 'Weight Maintenance'), ('gain', 'Muscle Gain')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
