# Generated by Django 5.2.7 on 2025-10-05 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_analyzer', '0002_meal_alter_userprofile_activity_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dietary_preferences',
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='lunch', max_length=20),
        ),
        migrations.AlterField(
            model_name='meal',
            name='tags',
            field=models.CharField(blank=True, help_text='e.g., vegetarian, gluten-free', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='activity_level',
            field=models.FloatField(blank=True, choices=[(1.2, 'Sedentary'), (1.375, 'Lightly active'), (1.55, 'Moderately active'), (1.725, 'Very active'), (1.9, 'Super active')], null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='allergies',
            field=models.TextField(blank=True, help_text='Comma-separated, e.g., peanuts, shellfish'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(blank=True, choices=[('lose', 'Weight Loss'), ('maintain', 'Maintenance'), ('gain', 'Muscle Gain')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='DailyIntakeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('food_name', models.CharField(max_length=100)),
                ('calories', models.FloatField()),
                ('protein_g', models.FloatField()),
                ('carbs_g', models.FloatField()),
                ('fat_g', models.FloatField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_analyzer.userprofile')),
            ],
        ),
    ]
